/* Copyright (c) 2008-2009-2010 Bluendo S.r.L.
 * See about.html for details about license.
 *
 * $Id: ResourceIDs.java 2325 2010-11-15 20:07:28Z luca $
 */

/**
 * 
 */
package it.yup.util;

/**
 * Holder for all resource string IDs
 */
public class ResourceIDs {

	public static final int STR_CLOSE = 1;
	public static final int STR_USERNAME = 2;
	public static final int STR_PASSWORD = 3;
	public static final int STR_WAIT = 4;
	public static final int STR_LOGIN = 5;
	public static final int STR_EXIT = 6;
	public static final int STR_DEBUG = 7;
	public static final int STR_CONTINUE = 8;
	public static final int STR_YES = 9;
	public static final int STR_NO = 10;
	public static final int STR_SEND = 11;
	public static final int STR_SAVE = 12;
	public static final int STR_ADDRESS = 13;
	public static final int STR_NICKNAME = 14;
	public static final int STR_GROUP = 15;
	public static final int STR_INSTRUCTIONS = 16;
	public static final int STR_SUBMIT = 17;
	public static final int STR_CANCEL = 18;
	public static final int STR_CLEAR = 19;
	public static final int STR_BACK = 20;
	public static final int STR_SERVER_NAME = 21;
	public static final int STR_CHOOSE = 22;
	public static final int STR_ACCEPT = 23;
	public static final int STR_PREV = 24;
	public static final int STR_NEXT = 25;
	public static final int STR_REGISTER = 26;
	public static final int STR_MISSING_FIELD = 27;
	public static final int STR_AUTORECONNECT = 28;
	public static final int STR_ABOUT = 29;
	public static final int STR_WARNING = 30;
	public static final int STR_HIDE = 31;
	public static final int STR_SHOW_INSTR = 32;
	public static final int STR_FILLLATER = 33;
	public static final int STR_DELETE = 34;
	public static final int STR_ERROR = 35;
	public static final int STR_MENU = 36;
	public static final int STR_OPTIONS = 37;
	public static final int STR_SELECT = 38;
	public static final int STR_SHOW_OFFLINE = 39;
	public static final int STR_GATEWAY_DISCOVERY = 40;
	public static final int STR_GATEWAYS = 41;
	public static final int STR_REG_GATEWAYS = 42;
	public static final int STR_HIDE_OFFLINE = 43;
	public static final int STR_CONTACT_TYPE = 44;
	public static final int STR_REFRESH = 45;
	public static final int STR_TRAFFIC = 46;
	public static final int STR_HELP = 47;
	public static final int STR_HELP_TEXT = 48;
	public static final int STR_DESC = 49;
	public static final int STR_REG_ERROR = 50;
	public static final int STR_HINT = 51;
	public static final int STR_GATEWAY_HINT = 52;
	public static final int STR_DISPLAYED_STATUS = 53;
	public static final int STR_LOADING = 54;
	public static final int STR_CONTACT_ID = 55;
	public static final int STR_SERVER_EXPLORE = 56;
	public static final int STR_NAME = 57;
	public static final int STR_NICK_NAME = 58;
	public static final int STR_WIZARD_TEXT = 59;
	public static final int STR_NEW_CONTACT = 60;
	public static final int STR_FT_STATUS = 61;
	public static final int STR_FINISHED = 62;
	public static final int STR_ONGOING = 63;
	public static final int STR_NO_FT = 64;
	public static final int STR_CONFIRM = 65;
	public static final int STR_WRONG_PWD = 66;
	public static final int STR_UNAVAILABLE = 67;
	public static final int STR_WAIT_ACCEPTANCE = 68;
	public static final int STR_DECLINED = 69;
	public static final int STR_WIZARD_GATEWAYS = 70;
	public static final int STR_KEY_CONFIGURATION = 71;
	public static final int STR_CLOSE_APPLICATION = 72;
	public static final int STR_OLD_MESSAGE = 73;
	public static final int STR_LOW_PRIORITY = 74;
	public static final int STR_PAUSE_APP = 75;
	public static final int STR_NEWS = 76;
	public static final int STR_SERVICES = 77;
	public static final int STR_CAPTCHA = 78;
	public static final int STR_UPDATE = 79;
	public static final int STR_UPDATE_TEXT = 80;
	public static final int STR_E_MAIL = 81;
	public static final int STR_SUBSCRIPTION = 82;
	public static final int STR_RESOURCES = 83;
	public static final int STR_JID = 84;
	public static final int STR_SUB_BOTH = 85;
	public static final int STR_SUB_TO = 86;
	public static final int STR_SUB_FROM = 87;
	public static final int STR_SUB_UNKNOWN = 88;
	public static final int STR_SUB_NONE = 89;
	public static final int STR_RECONNECT = 90;
	public static final int STR_ENABLE = 91;

	public static final int STR_WRITE = 100;
	public static final int STR_CHAT_WITH = 101;
	public static final int STR_CLEAR_HIST = 102;
	public static final int STR_MESS_PENDING = 103;
	public static final int STR_USE_URLS = 104;
	public static final int STR_ADD_USER = 105;
	public static final int STR_MORE = 106;
	public static final int STR_FORWARD_MESSAGE = 107;
	public static final int STR_FORWARD = 108;
	public static final int STR_TO = 109;
	public static final int STR_FORWARDED_TEXT = 110;
	public static final int STR_PARTICIPANTS = 111;
	public static final int STR_DISPLAYED_NAME = 112;
	public static final int STR_AUTOMATIC = 113;
	public static final int STR_MANUAL = 114;
	public static final int STR_OK = 115;

	public static final int STR_JABBER_ID = 200;
	public static final int STR_OPTIONAL = 201;
	public static final int STR_EMAIL_ADDRESS = 202;
	public static final int STR_NEW_USER = 203;
	public static final int STR_TITLE = 204;
	public static final int STR_REGFAIL_TITLE = 205;
	public static final int STR_REGFAIL_DESC = 206;
	public static final int STR_LOGFAIL_TITLE = 207;
	public static final int STR_LOGFAIL_DESC = 208;
	public static final int STR_ADVANCED_OPTIONS = 209;
	public static final int STR_CONNECTING_SVR = 210;
	public static final int STR_LOGGING_IN = 211;
	public static final int STR_GROUP_CHAT = 212;
	public static final int STR_CHOOSE_NAME = 213;
	public static final int STR_GROUP_CHAT_INVITATION = 214;
	public static final int STR_EXIT_MUC = 215;
	public static final int STR_JOINED_MUC = 216;
	public static final int STR_LEFT_MUC = 217;
	public static final int STR_TOPIC = 218;
	public static final int STR_SET_TOPIC = 219;
	public static final int STR_REG_UNALLOWED = 220;
	public static final int STR_ALREADY_EXIST = 221;
	public static final int STR_ENABLE_COMPRESSION = 222;
	public static final int STR_LOGIN_HINT = 223;
	public static final int STR_NOTE = 224;
	public static final int STR_ENABLE_TLS = 225;
	public static final int STR_STOP_LOGIN = 226;
	public static final int STR_KEY_HELP = 227;
	public static final int STR_KEY_SELECT_LEFT = 228;
	public static final int STR_KEY_SELECT_RIGHT = 229;
	public static final int STR_KEY_CONFIRM_LEFT = 230;
	public static final int STR_KEY_CONFIRM_RIGHT = 231;
	public static final int STR_KEY_PROCEED = 232;
	public static final int STR_KEY_ERROR_KEY = 233;
	public static final int STR_KEY_ERROR_SELECTION = 234;
	public static final int STR_KEY_PRESS = 235;
	public static final int STR_KEY_CONFIRM = 236;
	public static final int STR_KEY_CONFIGURE = 237;
	public static final int STR_CONNECTION_FAILED = 238;
	public static final int STR_CONNECTION_LOST = 239;
	public static final int STR_WRONG_USERNAME = 240;
	public static final int STR_CONNECTED = 241;
	public static final int STR_TLS_INITIALIZED = 242;
	public static final int STR_COMPRESSION_INITIALIZED = 243;
	public static final int STR_AUTHENTICATED = 244;
	public static final int STR_INITIALIZED = 245;
	public static final int STR_RESET_CONFIG = 246;
	public static final int STR_RESET_DATA = 247;
	public static final int STR_CLOSE_MUC = 248;
	public static final int STR_ROOM_NAME = 249;
	public static final int STR_ENTER_MUC = 250;
	public static final int STR_PERSISTENT = 251;
	public static final int STR_AUTOJOIN_YES = 252;
	public static final int STR_AUTOJOIN_NO = 253;
	public static final int STR_CREATE_GROUP_CHAT = 254;
	public static final int STR_AUTOJOIN_LAMPIRO = 255;
	public static final int STR_AUTOJOIN_OC = 256;
	public static final int STR_AUTOJOIN = 257;
	public static final int STR_INVITATION_SENT = 258;
	public static final int STR_CHANGE_NICK = 259;

	public static final int STR_COMMAND_INFO = 260;
	public static final int STR_DATA = 261;
	public static final int STR_CONNECTION = 262;
	public static final int STR_DATA_SUBMITTED = 263;
	public static final int STR_COMMAND_CANCELING = 264;
	public static final int STR_COMMAND_CANCELED = 265;
	public static final int STR_TASK_FINISHED = 266;
	public static final int STR_TASK_ERROR = 267;
	public static final int STR_SERVER_TYPE = 268;

	public static final int STR_MESSAGE_TO = 300;
	public static final int STR_FILL_FORM = 500;
	public static final int STR_SEND_MESSAGE = 700;
	public static final int STR_CHAT = 701;
	public static final int STR_EDIT_CONTACT = 702;
	public static final int STR_ADD_CONTACT = 703;
	public static final int STR_DELETE_CONTACT = 704;
	public static final int STR_CHANGE_STATUS = 705;
	public static final int STR_ROSTER_TITLE = 706;
	public static final int STR_QUERYCMD = 707;
	public static final int STR_LISTCMD = 708;
	public static final int STR_RELOAD_CONTACT = 709;
	public static final int STR_PENDINGTASK = 710;
	public static final int STR_SEE_DETAILS = 711;
	public static final int STR_CAPTURE_IMAGE = 712;
	public static final int STR_CAPTURE = 713;
	public static final int STR_IMAGE = 714;
	public static final int STR_CONTACTS = 715;
	public static final int STR_FILE_NAME = 716;
	// public static final int STR_START = 717;
	public static final int STR_ASK_FT = 718;
	public static final int STR_FT = 719;
	public static final int STR_CAPTURE_AUDIO = 720;
	public static final int STR_AUDIO = 721;
	public static final int STR_STOP = 722;
	public static final int STR_PLAY = 723;
	public static final int STR_MM_ALBUM = 724;
	public static final int STR_MM_SAVE = 725;
	public static final int STR_FT_ERROR = 727;
	public static final int STR_DECODE_ERROR = 728;
	public static final int STR_SEND_FILE = 729;
	public static final int STR_REFRESH_ROSTER = 730;
	public static final int STR_SEND_IMAGE = 731;
	public static final int STR_SEND_AUDIO = 732;
	public static final int STR_UNGROUPED = 733;
	public static final int STR_SEARCH = 734;
	public static final int STR_HIGHLIGHTS = 735;
	public static final int STR_HANDLE_GROUPS = 736;
	public static final int STR_GROUP_LIST = 737;
	public static final int STR_NEW_GROUP = 738;
	public static final int STR_EXISTING_GROUPS = 739;
	public static final int STR_MOVE = 740;
	public static final int STR_OPEN = 741;
	public static final int STR_EXPANDED = 742;
	public static final int STR_LOGOUT = 743;
	public static final int STR_IS = 744;
	public static final int STR_ONLINE = 745;
	public static final int STR_OFFLINE = 746;
	public static final int STR_SEND_GRP_MSG = 747;
	public static final int STR_SIZE = 748;
	public static final int STR_CAPTURE_CAPTION = 749;
	public static final int STR_RESEND_AUTH = 751;
	public static final int STR_REREQUEST_AUTH = 752;
	public static final int STR_EMPTY_ALBUM = 753;
	public static final int STR_MANAGE_GC = 754;
	public static final int STR_SCARY_MUC = 755;
	public static final int STR_NETWORKS = 756;
	public static final int STR_LOG = 757;
	public static final int STR_REMOVE_NETWORK = 758;
	public static final int STR_ACTIVE_SESSIONS = 759;
	public static final int STR_CHG_GROUP_NAME = 760;
	public static final int STR_NEW_VERSION_TITLE = 761;
	public static final int STR_NEW_VERSION_TEXT = 762;

	public static final int STR_SET_STATUS = 800;
	public static final int STR_CHOOSE_STATUS = 801;
	public static final int STR_STATUS_MESSAGE = 802;
	public static final int STR_PRIORITY = 803;
	public static final int STR_RESOURCE = 804;

	public static final int STR_SUBSCRIPTION_CONFIRM = 900;
	public static final int STR_SUBSCRIPTION_REQUEST_FROM = 901;
	public static final int STR_SUBSCRIPTION_ACCEPT = 902;
	public static final int STR_ACCEPT_ALL = 903;
	public static final int STR_ACCEPT_ALWAYS = 904;
	public static final int STR_SUBSCRIPTION_REQUEST = 905;
	//	public static final int STR_FT_DECLINED = 906;
	//	public static final int STR_FT_ACCEPTED = 907;
	public static final int STR_FT_SENT = 908;
	// public static final int STR_FT_NOT = 909;
	// public static final int STR_FT_RECEIVER = 910;
	public static final int STR_UPLOAD_TEXT = 911;
	public static final int STR_REJECT = 912;

	public static final int STR_CMDSCREEN_TITLE = 1001;
	public static final int STR_EXECUTE = 1002;
	public static final int STR_TASKHISTORY_TITLE = 1003;
	public static final int STR_NO_COMMAND = 1004;
	public static final int STR_AVAILABLE_COMMANDS = 1005;

	public static final int STR_COMMAND_ERROR = 1101;

	public static final int STR_OPTIONS_SETUP = 1200;
	public static final int STR_WHEN_NEW_MESSAGES = 1201;
	public static final int STR_VIBRATE_IF = 1202;
	public static final int STR_HIDDEN = 1203;
	public static final int STR_SHOW = 1204;
	public static final int STR_PLAY_TONE_IF = 1205;
	public static final int STR_VOLUME = 1206;
	public static final int STR_KEEPALIVE = 1207;
	public static final int STR_SETTINGS_EFFECT = 1208;
	public static final int STR_COLOR = 1209;
	public static final int STR_COLOR_RED = 1210;
	public static final int STR_COLOR_GREEN = 1211;
	public static final int STR_COLOR_BLUE = 1212;
	public static final int STR_FONT_SMALL = 1213;
	public static final int STR_FONT_MEDIUM = 1214;
	public static final int STR_FONT_BIG = 1215;
	public static final int STR_FONT_SIZE = 1216;
	public static final int STR_RESET_OPTIONS = 1217;
	public static final int STR_HISTORY_SIZE = 1218;
	public static final int STR_MM_SIZE = 1219;
	public static final int STR_QWERTY = 1220;
	public static final int STR_COLOR_ALEF = 1221;
	public static final int STR_CAMERA_RESOLUTION = 1222;
	public static final int STR_RESOLUTION_DEFAULT = 1223;
	public static final int STR_CAMERA_LOW = 1224;
	public static final int STR_CAMERA_MEDIUM = 1225;
	public static final int STR_CAMERA_HIGH = 1226;
	public static final int STR_CAMERA_HUGE = 1227;
	public static final int STR_CAMERA_ERROR = 1228;
	public static final int STR_MENU_FONT_SIZE = 1229;

	public static final int STR_UNREAD_NEWS = 1300;
	public static final int STR_NEWS_SIZE = 1301;
	public static final int STR_MARK_UNREAD = 1302;
	public static final int STR_MSG_FORWARDED = 1303;
	public static final int STR_SHOW_ALL = 1304;
	public static final int STR_SHOW_UNREAD = 1305;
	public static final int STR_MARK_ALL = 1306;
	public static final int STR_REMOVE_FEED = 1307;
	public static final int STR_TO_LOAD = 1308;
	public static final int STR_SYNC = 1309;
	public static final int STR_SYNC_ASKED = 1310;
	public static final int STR_SYNC_ALL = 1311;
	public static final int STR_EMPTY_NEWS = 1312;
	public static final int STR_ONLINE_SYNC_ALL = 1313;
	public static final int STR_STOP_SYNC_ALL = 1314;
	public static final int STR_SYNC_STATUS = 1315;
	public static final int STR_VISIT_ADVER = 6002;
	public static final int STR_FULL_VERSION = 6003;

	public static final int STR_SECURED_CONNECTION = 5009;
	public static final int STR_WRONG_KEY = 5011;

	public static final int STR_GLIDER = 5001;
	public static final int STR_GEC = 5002;
	public static final int STR_OOROS_NEWS = 5003;
	public static final int STR_MONEIRO = 5004;
	public static final int STR_GLIDER_LOGIN = 5005;
	public static final int STR_CREATE_MODIFY = 5006;
	public static final int STR_MESSENGER = 5007;
	public static final int STR_OOROS_ADVICE = 5008;
	public static final int STR_CONFIRM_SUBSCRIPTION = 5010;
	public static final int STR_ACTION = 5012;
	public static final int STR_POST = 5013;
	public static final int STR_ALSO = 5014;
	public static final int STR_TAGS = 5015;
	public static final int STR_LIKE = 5016;
	public static final int STR_SUBSCRIBE = 5017;
	public static final int STR_FEED_SEARCH = 5018;
	public static final int STR_NO_ITEMS_FOUND = 5019;
	public static final int STR_LIKE_SENT = 5020;

	public static final int STR_APP_SWITCH = 6001;
	public static final int STR_ALLOWED_NETWORKS = 6004;
	public static final int STR_CONN_WIFI = 6005; // Wifi
	public static final int STR_CONN_DIRECT = 6006; // Direct Connection
	public static final int STR_CONN_BIBS = 6007; // Blackberry Internet Service
	public static final int STR_CONN_BES_MDS = 6008; // Bes/MDS
	public static final int STR_RETRY = 6009;
	public static final int STR_MINIMIZE = 6010;
	public static final int STR_ASKPERMISSION = 6011;
	public static final int STR_CONN_DIRECT_AUTO = 6012; // Direct Connection automatic

	/* uninstantiable */
	private ResourceIDs() {
	}
}
